### ISSUE TITLE
Enable user to provide PluralForms line 

### ISSUE THREAD

**Issue by colindean** [xitrum-framework/scala-xgettext#13]
I _think_ I need a way to specify the plural forms formula.

https://www.gnu.org/software/gettext/manual/gettext.html#Plural-forms

`Plural-Forms: nplurals=2; plural=n != 1;` is the default for English, and would make a sane default for this option. Maybe this can be passed in through a compiler property such as `'-P:xgettext_plurals:nplurals=2; plural=n != 1'`

**Comment by colindean** [comment]
I've got a fix ready for this, but I have to go through my company's legal team before I can submit it. I expect that to take about a week 😒 

I've simply added the above default to the headers.

**Comment by colindean** [comment]
I've finished a revision that adds the `Plural-Forms` header dynamically, defaulting to the formula for English and many other languages. The user can choose the source language by two-character ISO 639-1 code to use a formula stored in a table in the source, or pass the raw formula to be used. Both of these are done via compiler parameters, just like `t:` options.

**Comment by ngocdaothanh** [comment]
I think we can design like this:

* If language code option is specified, generate pot file containing corresponding `Plural-Forms` line for the language, and the correct number of `msgstr[xxx]` entries.
* If language code option is not specified, generate pot file without the above.

In your pull request, please also update README:
https://github.com/xitrum-framework/scala-xgettext/blob/master/README.rst

Thanks!
