### ISSUE TITLE
Pass POT creation date as property or use current time

### ISSUE THREAD

**Issue by colindean** [xitrum-framework/scala-xgettext#14]
`"POT-Creation-Date: \n"` is all that's there. Why not populate it?

**Comment by ngocdaothanh** [comment]
There are several reasons:

* You usually use Git, SVN etc. to control source code. They can give you date info.
* Various people can argue which date to use: https://www.drupal.org/node/531916
* Setting it may bring more headache: https://github.com/cakephp/cakephp/issues/5887

In short, if you really want, you can set the date manually by yourself.

**Comment by colindean** [comment]
Should that header then be removed from the default header, or commented out?

**Comment by ngocdaothanh** [comment]
If it doesn't cause problem, I think just leave it.
