### ISSUE TITLE
Throw exception if the arguments singular, plural, and context are not literal constant string

### ISSUE THREAD

**Issue by c0d3r85** [xitrum-framework/scala-xgettext#17]
Our legacy project used "t" with constants. We created pot file manualy.
For example:
```scala
  val titleKey = "Some title"
  ...
  val messageTitle = t(titleKey)
```
pot file look like this:
```
...
msgid titleKey
msgstr ""
...
```
Can we extract constant value or show warning on such cases?

**Comment by ngocdaothanh** [comment]
I've just released v1.5.0.
Scala 2.12 is supported.
