### ISSUE TITLE
Add option to ignore non-literal-constant strings instead of throwing an Exception

### ISSUE THREAD

**Issue by fbaierl** [xitrum-framework/scala-xgettext#19]
```
The arguments ``singular``, ``plural``, and ``context`` MUST be literal constant string, like in the above examples. Otherwise exception will be thrown during compilation.
```
Would it be possible to add a configuration option that changes this behavior into ignoring any string that is not a literal constant string instead of throwing an Exception? If you deem this useful, I could look into making a PR that adds this behavior.

**Comment by fbaierl** [comment]
I went ahead and made a PR: https://github.com/xitrum-framework/scala-xgettext/pull/20

**Comment by ngocdaothanh** [comment]
Hi, thank you for the suggestion and the PR. Can you explain why do you want this feature? I want to understand the story behind this feature.

**Comment by fbaierl** [comment]
Close b/c done: https://github.com/xitrum-framework/scala-xgettext/pull/20
