### ISSUE TITLE
Handling interpolated strings?

### ISSUE THREAD

**Issue by colindean** [xitrum-framework/scala-xgettext#8]
We're observing a behavior when using interpolated strings. If our code is:

    println(t(s"Sending node"))

Then the output in i18n.pot is:

    msgid new StringContext(scala.this.Predef.wrapRefArray[String](Array[String]{"Sending node"})).s(immutable.this.Nil)

Where interpolation is actually used:

    println(t(s"Sending node ${node.name}"))

we see:

    msgid new StringContext(scala.this.Predef.wrapRefArray[String](Array[String]{"Sending node ", ""})).s(scala.this.Predef.genericWrapArray[Any](Array[Any]{StreamOfIndexables.this.channel().getClass().toString()}))

Can we not use interpolation with scala-xgettext?

**Comment by ngocdaothanh** [comment]
Yes, the thing passed to `t` should be a literal string.

You can change:
```
println(t(s"Sending node ${node.name}"))
```

To:
```
println(t("Sending node %s").format(node.name))
```

**Comment by colindean** [comment]
Ah, that's unfortunate. 

I'm going to think on this a little more when I get back to work in the morning (US east coast bedtime now).

Can you think of a way that scala-xgettext could be extended to support interpolation? I'm not sure if it's possible, given how interpolation is handled (at compile time, iirc).

**Comment by ngocdaothanh** [comment]
It's not "unfortunate".
Think about it.
When you write `println(t(s"Sending node ${node.name}"))`, what do you want to be extracted to your language file?

**Comment by colindean** [comment]
I don't know what I'd expect. If I ignored what I know about how Scala handles interpolated strings, I would expect

    msgid "Sending node ${node.name}"

just as if it wasn't interpolated. This obviously is not very possible, because, if I understand scala-xgettext correctly, it extracts each strings from the AST where the string is passed to the `t` method on a certain class (or however it's been configured). Thus, scala-xgettext doesn't even know what the original code looks like.

Could scala-gettext somehow modify the AST, injecting the `string.format(params)` on the fly by modifying the StringContext? I'm just throwing ideas out there.

**Comment by lefou** [comment]
Using `String.format` method is in general not very translation friendly, as you sometimes need to reorder the arguments in the translation and this is not possible with `String.format`. That's why it is common to use indexed parameters. In Java (and of course also Scala) that kind of placeholders is used by `MessageFormat.format` and supported by GNU (x)gettext. It looks like this: `"{0} errors found: {1}"`.

So, one feasible expectation could be:

```
msgid "This has {0} used {1}"
```

Nice to have: Detect, when the same pure expression is used in the placeholder and reuse the same index: e.g. `s"you have ${n} of ${n}"` => `"you have {0} of {0}"`.

**Comment by ngocdaothanh** [comment]
> String.format method is in general not very translation friendly

You can use placeholders in String.format like this:

```
// 1$ and 2$ are placeholders
String.format(t("%1$s says hello to %2$s, then %2$s says hello back to %1$s"), name1, name2)
```

I've updated the README to explain about using placeholders in `String.format` and `MessageFormat.format`.

I'll close this issue now.
